### ISSUE TITLE
output of plan can become very long

### ISSUE THREAD

**Issue by joakimhellum-in** [hashicorp/terraform-github-actions#1]
Thanks alot for these scripts. Appreciate many changes are coming to Terraform, but would like to propose minor changes to avoid what is potentially very long output in pull request reviews for Terraform GitHub Actions:

1. Collapse long output if it's longer than 25 lines using the `<details>` tag.
2. Remove everything before the first separator in output of plan (for example there could be alot of "Refreshing state..." lines).

For point 1: This is bad example but I guess it could be possible to do something similar to this on the output:

```bash
sed -n -r '/-{72}/,/-{72}/{ /-{72}/d; p }'
```

For point 2 I guess it could be possible to do something like this:
```bash
if [ $(echo "$OUTPUT" | wc -l) -gt 25 ]; then
    COMMENT="#### \`terraform plan\` Failed
<details><summary>Show Output</summary>

\`\`\`diff
$FMT_PLAN
\`\`\`

</details>
"
fi
```

Would be happy to make PR for this but wanted to raise the issue first.

Thanks for considering,

**Edit:** Just noticed both these issues are already addressed in Atlantis, that is maintained by the same person who created these scripts :)

**Comment by lkysow** [comment]
Hi Joakim, sorry for the delay in responding.

I think those changes are a great idea. If you have bandwidth for a PR, that would be much appreciated!
