### ISSUE TITLE
Bot is not commenting locked PRs

### ISSUE THREAD

**Issue by alexbde** [hashicorp/terraform-github-actions#100]
Doing some exploratory testing I stumbled upon this situation: github-actions bot normally comments with output of terraform plan. When I lock the PR there are no more comments. I know this is what locking is for but a bot should be able to reply IMHO.

Is this behaviour intended? Or limited by GitHub API? Then I'll file an issue at GitHub Actions.

Example: Between locking and unlocking PR in the image below it did `terraform plan` action, so I'd expected a comment just like the other ones.

![Image](https://user-images.githubusercontent.com/17784818/68149271-e1ecef00-ff3d-11e9-85c5-ca1997dd166f.png)

**Comment by sudomateo** [comment]
> Is this behaviour intended? Or limited by GitHub API? Then I'll file an issue at GitHub Actions.
I believe this is intended behavior. Once the conversation is locked, only collaborators can continue to leave comments. I'm assuming the `GITHUB_TOKEN` that the GitHub Actions bot uses is not seen as a collaborator and thus cannot comment once the conversation is locked.

All this project does is use the `GITHUB_TOKEN` as detailed [here](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#github_token-secret) to authenticate and submit a comment via the GitHub API.

**Comment by alexbde** [comment]
Okay, I'll discuss it at [GitHub Community](https://github.community/t5/GitHub-Actions/Bot-quot-github-actions-quot-not-allowed-to-comment-locked-PR/m-p/36977).
