### ISSUE TITLE
Terraform validate not working with v0.6.0

### ISSUE THREAD

**Issue by alexbde** [hashicorp/terraform-github-actions#109]
Terraform validate fails running Terraform GitHub Actions v0.6.0 with message `Error: Could not satisfy plugin requirements`.

I uploaded a minimal example here: https://github.com/alexbde/terraform-demo/pull/2/checks
As you can see I only upgraded versions from v0.5.4 to v0.6.0.

It worked before, see https://github.com/alexbde/terraform-demo/pull/1/checks

**Comment by alexbde** [comment]
Looks like `terraform init` is causing the issue. Running it ends with message `Terraform initialized in an empty directory!` instead of initializing provider plugins and ending with `Terraform has been successfully initialized!` (compare step "Terraform initialize" in [PR#1](https://github.com/alexbde/terraform-demo/pull/1/checks) and [PR#2](https://github.com/alexbde/terraform-demo/pull/2/checks)).

Downgrading `terraform init` to Terraform Actions v0.5.4 causes `terraform validate` to run like expected but lets `terraform plan` fail with message `stat : no such file or directory`: https://github.com/alexbde/terraform-demo/pull/3/checks

**Comment by sudomateo** [comment]
Should be fixed in #111 which is released as [v0.6.1](https://github.com/hashicorp/terraform-github-actions/releases/tag/v0.6.1).

**Comment by alexbde** [comment]
Looks very good, thank you!

https://github.com/alexbde/terraform-demo/pull/4/checks
