### ISSUE TITLE
Support modules in private repositories

### ISSUE THREAD

**Issue by reegnz** [hashicorp/terraform-github-actions#120]
I am referencing a terraform module in a private github repository and I get the following error:
```
Error: Failed to download module

Could not download module "example" (main.tf:1) source code from
"git::https://github.com/reegnz/terraform-modules.git?ref=v1.2.3":
error downloading
'https://github.com/reegnz/terraform-modules.git?ref=v1.2.3':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/example'...
fatal: could not read Username for 'https://github.com': No such device or
address
```

Suggestion:
When passing GITHUB_TOKEN, configure git to use it for pulling any other repository from github as well:
~~~
git config --global http.https://github.com/.extraheader 'AUTHORIZATION: basic $GITHUB_TOKEN
~~~

**Comment by Jyoti492** [comment]
@reegnz : is your problem resolved ?

**Comment by reegnz** [comment]
Not really. What I need is for terraform to pull a module from a private repo.

**Comment by alexbde** [comment]
We use private repos as module source via SSH:

    module "example" {
      source = "git@github.com:example-org/example-modules//modules/example?ref=v0.1.0"
    }

With following solution / workaround in our Terraform workflow:

    steps:
    ...
      - name: Terraform initialize
        uses: hashicorp/terraform-github-actions@v0.6.3
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.GITHUB_ADMIN_SSH_PRIVATE_KEY }}' > id_rsa
            && echo 'github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}' > known_hosts
            && chmod 400 id_rsa known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
          tf_actions_comment: true
    ...

Maybe that's an option for you, too.

**Comment by davidvasandani** [comment]
Is it possible to pull from a private repo as a module source via HTTPS?

**Comment by allejo** [comment]
@davidvasandani it is possible, something like #139 accomplishes that

**Comment by kalib** [comment]
Any news on this? I tried so many options.. but still it all fails to me. 

I'm using:

`name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa
            && echo 'github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}' > known_hosts
            && chmod 400 id_rsa known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}`

But my init still fails:

`
Could not download module "launch_configuration" (main.tf:6) source code from
"git@github.com:kalib/terratestmodules.git": error downloading
'ssh://git@github.com/kalib/terratestmodules.git': /usr/bin/git exited with
128: Cloning into '.terraform/modules/launch_configuration'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



Error: Failed to download module

Could not download module "launch_configuration" (main.tf:6) source code from
"git@github.com:kalib/terratestmodules.git": error downloading
'ssh://git@github.com/kalib/terratestmodules.git': /usr/bin/git exited with
128: Cloning into '.terraform/modules/launch_configuration'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by kalib** [comment]
> hashicorp/terraform-github-actions@

I tried exactly the same, but with hashicorp/terraform-github-actions@master and it fails. Why exactly you decided to use hashicorp/terraform-github-actions@v0.6.3? Just curious. In any case, it still fails for me.. I tried both.

**Comment by alexbde** [comment]
> Why exactly you decided to use hashicorp/terraform-github-actions@v0.6.3? Just curious. In any case, it still fails for me.. I tried both.

That was just the latest version when I wrote the code. I pin versions of GitHub actions as best practice so I can test new releases before rolling out to production.

**Comment by mataneine** [comment]
@alexbde I modified your solution so it wont create id_rsa & known_hosts on every pull and also replaced github.com public key with ssh-keyscan command

```
steps:
...
  - name: ssh-add
    run: |
      echo "${{ secrets.GITHUB_SSH_PRIVATE_KEY }}" > id_rsa
      ssh-keyscan github.com > known_hosts
      chmod 400 id_rsa known_hosts
  - name: 'terraform init'
    uses: hashicorp/terraform-github-actions@master
    with:
      tf_actions_version: 0.12.20
      tf_actions_subcommand: 'init'
      tf_actions_comment: true
    env:
      GIT_SSH_COMMAND: 'ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts'
...
```

**Comment by andrevtg** [comment]
If valid SSH keys are provided you can pretty much use them. My CI is Gitlab, so my job runs in a container and such keys are mounted directly as files in /opt/shh. Module source is in the SSH form like "git@github.com:example-org/example-modules.......".

You just have to run something like this early in your job:

```
mkdir ~/.ssh
cp /opt/ssh/id_something ~/.ssh/id_rsa
cp /opt/ssh/id_something.pub ~/.ssh/id_rsa.pub
chmod 700 ~/.ssh/
chmod 600 ~/.ssh/id_rsa
chmod 644 ~/.ssh/id_rsa.pub
```
