### ISSUE TITLE
Terraform Cloud queue from github actions

### ISSUE THREAD

**Issue by russellc92** [hashicorp/terraform-github-actions#128]
Hello,

I was wondering if it was possible to start a Terraform Cloud workspace run/queue via GitHub actions?

Many thank

**Comment by sudomateo** [comment]
Hello,

It is possible. You'll have to use the `remote` backend in your Terraform configuration and then configure your GitHub Actions YAML to pass in the required authentication for the `remote` backend.

Some references can be found below.
- https://www.terraform.io/docs/github-actions/common-tasks/backends.html
- https://www.terraform.io/docs/github-actions/common-tasks/workspaces.html

**Comment by russellc92** [comment]
Awesome! Thank you for letting me know and for the links
