### ISSUE TITLE
[Feature Request] Support berglas

### ISSUE THREAD

**Issue by sonots** [hashicorp/terraform-github-actions#131]
We use https://github.com/GoogleCloudPlatform/berglas to avoid embed credentials in .tf file.

What we need to support berglas is to change the internal command `terraform` to

    berglas exec -- terraform

**Comment by sonots** [comment]
Seems that we need to install `berglas` itself inside main.sh, too.

**Comment by sudomateo** [comment]
Thank you for the issue! Unfortunately, this is not something we'll be pursuing.
