### ISSUE TITLE
The "tf_actions_plan_has_changes" output is not working as expected

### ISSUE THREAD

**Issue by philippschulte** [hashicorp/terraform-github-actions#135]
The `tf_actions_plan_has_changes` output isn't working as expected after the refactor. In the current implementation the output variable is only set if the plan's exit code is not equal to `0`. This means the output gets only set if the plan has changes or if there is an error but never if the plan succeeded with empty diff (no changes).

The reason is if the plan succeeds with empty diff (no changes) the plan action exits before the output gets set to `false`. Because of this issue other actions who rely on the plan's action output can't do their work!

@sudomateo it would be great if this issue could be prioritized and addressed as soon as possible because it was already implemented in #73 and working before the refactor. Thanks in advance.

**Comment by sudomateo** [comment]
Ha. @philippschulte Thank you for submitting that pull request. That method was my initial thought as well. After comparing the two I think I'm going to go with your method since it keeps the code path a bit cleaner. The `exit` ensures it'll never get to the second `echo` where the output is set.

**Comment by sudomateo** [comment]
I'll get this out in `v0.7.1`. Thank you!

**Comment by sudomateo** [comment]
This is released in `v0.7.1`.
