### ISSUE TITLE
Suggestion: Avoid multiple installations of the same terraform version

### ISSUE THREAD

**Issue by kjs222** [hashicorp/terraform-github-actions#152]
We have a use case that I imagine is quite typical - a workflow with multiple steps to run various commands (init, plan, etc), all using the same terraform version. In that use case, the same version of terraform is downloaded on each step of the workflow. We see the following output in each step:

```
Downloading Terraform v0.12.13
Successfully downloaded Terraform v0.12.13
Unzipping Terraform v0.12.13
Successfully unzipped Terraform v0.12.13
```

Assuming the downloaded versions are (or can be) in a directory that accessible between steps, it would be great if there could be a check for whether the version has been installed, and avoid the extra installations when possible. Since it's possible to set a different terraform version for each step, it may also be necessary to track/manage the version of the terraform executable in the path.

**Comment by sudomateo** [comment]
This is a valid suggestion. However, I do not believe there's a way to cache data between steps that use Docker instead of JavaScript.

**Comment by kjs222** [comment]
Ah gotcha. I was hoping there might be a way to take advantage of the file system on the runner via `$GITHUB_WORKSPACE` or other.

**Comment by sudomateo** [comment]
Hmm. I would like to avoid installing binaries into the `GITHUB_WORKSPACE` location since that is supposed to be used for the repository content itself. I wonder if there's another location that persists between steps.

**Comment by mmindenhall** [comment]
https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#filesystems-on-github-hosted-runners

Perhaps install under `$HOME/bin`?
