### ISSUE TITLE
jq: Argument list too long

### ISSUE THREAD

**Issue by heydonovan** [hashicorp/terraform-github-actions#16]
I'm trying to setup GitHub Actions for the first time. The goal is to have `terraform fmt` run on the specific file that's listed in a pull request. Looks like you can only do so on a directory, so trying to figure out how to dynamically figure that out based on file path. I've the same workflow from the official docs. I'm thinking because every file needs to be formatted, that it runs into this issue?

```
Step 10/11 : COPY entrypoint.sh /entrypoint.sh
 ---> 46a7ac06a80c
Step 11/11 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 537ed01456ed
 ---> 19063ae06c35
Successfully built 19063ae06c35
Successfully tagged gcr.io/gct-12-o8j5btwcsznlu4r352a0flm/ec7b5798739a0281d7439c11003205df079f23dcbdc5bda247eb21e0945a25dc/dc2b4b57b2c0f541e99a0d9e1a1e9cdd48c7e393a9f23d0068f27104e3230fa0:9fbe06d0103176b8a075ad1f2be9c8b041485afdbe442ba33d16a01769892b04
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
...
...
/entrypoint.sh: line 36: jq: Argument list too long

### FAILED terraform-fmt 21:01:16Z (32.528s)
```

**Comment by lkysow** [comment]
Yeah it must be that the comment it's going to write is too big. Even if we fixed the jq error I think we'd probably run into other errors due to the huge comment.

`terraform fmt` can't run on a single file:
```
terraform fmt --help
Usage: terraform fmt [options] [DIR]
```

So I'd recommend either running `terraform fmt` on your whole repo yourself or removing that step from your workflow.

**Comment by TarekAS** [comment]
This happened to us with ```terraform plan``` as well. We have a module with over 80 resources. Any alternatives?
