### ISSUE TITLE
Proper version tagging

### ISSUE THREAD

**Issue by ruzickap** [hashicorp/terraform-github-actions#163]
Hello.

Would it be possible to do a proper tagging for this project please? 

Maybe good starting point is here: https://github.com/actions/checkout 
They are using versions like:

* `v2` -> `v2.0.0`
* `v1` -> `v1.2.0`

It would be really handy to use something like `v1` instead of specifying the exact version only `v0.8.0` (or `master`):

```yaml
    - uses: hashicorp/terraform-github-actions@v1
```

Thank you...

**Comment by sudomateo** [comment]
Work on v1 is currently underway. Once it is released this will become a reality. Thank you!
