### ISSUE TITLE
Unable to add sensitive output to `tf_actions_output` without it being displayed in logs

### ISSUE THREAD

**Issue by marklawlor** [hashicorp/terraform-github-actions#164]
## Issue

I would like to pass a sensitive output from terraform to another step using `tf_actions_output`. However the `output` command always displays the sensitive output in the CI logs.

## Proposal

Either add a `silent` option to the `output` command or respect the `sensitive` option of outputs.

**Comment by ericsampson** [comment]
`sensitive` support would be great.
