### ISSUE TITLE
GCP credentials suppport

### ISSUE THREAD

**Issue by kunickiaj** [hashicorp/terraform-github-actions#19]
TF expects a path to a JSON file (doesnt support the JSON in an env var AFAIK).
If you need access to GCP creds either for provider or state, what's the recommended way to deal with this and/or is it even possible currently?

My thinking right now is to see if you'd accept a patch that worked this way:

* accept a github secret (env var) with the JSON or base64 encoded JSON credentials file,
* decode and write it to FS and set the GOOGLE_CREDENTIALS env var such that terraform can find it.
* clean up the file

Not my preferable solution, but the only way i can think of without modifying terraform itself.

**Comment by lkysow** [comment]
Are you sure you can't use the contents of the JSON in the environment variable?

>  Either the path to or the contents of a service account key file in JSON format

https://www.terraform.io/docs/providers/google/provider_reference.html#credentials-1

**Comment by lkysow** [comment]
Closing because I haven't heard back.
