### ISSUE TITLE
Support multiple Terraform versions

### ISSUE THREAD

**Issue by lkysow** [hashicorp/terraform-github-actions#23]
Currently, you must use the latest version of Terraform. It would be great to support something like a `TF_ACTION_TF_VERSION` environment variable.

**Comment by aharden** [comment]
On this note, @lkysow I'm wondering if you could publish a version of these tools that use TF v.0.11.14; I adopted that for my TF v0.11.x configs not knowing that the state file change would break the existing TF GH action compatibility (I was running v0.1.3).  Moving up to TF GH actions v0.3.2 introduced new validation errors specific to TF v0.12.x.  Thanks for considering.

**Comment by lkysow** [comment]
Hi, I would suggest you fork this repo and change the Dockerfile instructions as detailed here: https://www.terraform.io/docs/github-actions/terraform-versions.html

That's probably the fastest way to get going again.

**Comment by aharden** [comment]
Will do, thanks.

**Comment by sudomateo** [comment]
I'm working on a rewrite that will add this functionality. Stay tuned!

**Comment by siddharthgoel88** [comment]
> I'm working on a rewrite that will add this functionality. Stay tuned!

Really looking forward to this @sudomateo :+1:  Any rough timeline when this feature might be available ?

**Comment by sudomateo** [comment]
Should be fixed in #88.
