### ISSUE TITLE
terraform-fmt fails silently

### ISSUE THREAD

**Issue by mindmelting** [hashicorp/terraform-github-actions#27]
### Release
v0.3.1

### Description
The `fmt` action fails silently on a Terraform repo that passes `terraform fmt` locally. There is no ouput in the Github Action logs or any comments on the PR that describes why it has failed.

### Output
```
### STARTED terraform-fmt 10:33:49Z

Already have image (with digest): gcr.io/github-actions-images/action-runner:latest

### FAILED terraform-fmt 10:34:00Z (10.782s)
```

### Github Action Workflow
```
workflow "Terraform Enterprise" {
  resolves = "terraform-plan"
  on = "pull_request"
}

action "filter-to-pr-open-synced" {
  uses = "actions/bin/filter@master"
  args = "action 'opened|synchronize'"
}

action "terraform-fmt" {
  uses = "hashicorp/terraform-github-actions/fmt@0.3.1"
  needs = "filter-to-pr-open-synced"
  secrets = ["GITHUB_TOKEN"]
}

action "terraform-init" {
  uses = "hashicorp/terraform-github-actions/init@0.3.1"
  needs = "terraform-fmt"
  secrets = ["GITHUB_TOKEN", "TF_ACTION_TFE_TOKEN"]
  env = {
    TF_ACTION_TFE_HOSTNAME = "app.terraform.io"
  }
}

action "terraform-validate" {
  uses = "hashicorp/terraform-github-actions/validate@0.3.1"
  needs = "terraform-init"
  secrets = ["GITHUB_TOKEN"]
}

action "terraform-plan" {
  uses = "hashicorp/terraform-github-actions/plan@0.3.1"
  needs = "terraform-validate"
  secrets = ["GITHUB_TOKEN", "TF_ACTION_TFE_TOKEN"]
  env = {
    TF_ACTION_TFE_HOSTNAME = "app.terraform.io"
  }
}
```

**Comment by lkysow** [comment]
* Are you running locally with the same version of Terraform?
* It should post something to the pull request, are you not seeing that?
* One way to debug would be to fork this repo and add a `set -x` to https://github.com/hashicorp/terraform-github-actions/blob/master/fmt/entrypoint.sh#L2. Then change your workflow to
  ```
  uses = "mindmelting/terraform-github-actions/plan@master"
  ```

**Comment by mindmelting** [comment]
Super odd - if I use the hashicorp `master`, it works fine - reverting back to `0.3.1` it fails again.

**Comment by alex** [comment]
FWIW I ran into this same thing when I specified `@<full-sha1>`, switching to `@v0.3.1` and it worked fine.
