### ISSUE TITLE
HCL Action syntax depecration

### ISSUE THREAD

**Issue by ns-phennessy** [hashicorp/terraform-github-actions#40]
Via: https://developer.github.com/actions/
> The documentation at https://developer.github.com/actions and support for the HCL syntax in GitHub Actions will be deprecated on September 30, 2019. Documentation for the new limited public beta using the YAML syntax is available on https://help.github.com. See "Automating your workflow with GitHub Actions" for documentation using the YAML syntax.

The official [Terraform docs](https://www.terraform.io/docs/github-actions/getting-started/index.html) show examples using the HCL syntax. Github said they're deprecating this, but it did not work at all for me. 

I was able to translate into the new syntax here and now it works! Here it is in all it's glory:
https://github.com/servers-tf/infrastructure/blob/master/.github/workflows/terraform.yml

Figured I would share this since I love automating my Git repos and am very excitied to have a easy integration with Terraform and Github :)

**Comment by dobber** [comment]
Thank you.
How would that work with multiple directories and workspaces?

**Comment by shawnmclean** [comment]
@ns-phennessy Your `plan` is failing about no configuration. Did you ever get around this? Mine is also failing there too.

`Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.
##[error]Docker run failed with exit code 1`

**Comment by tomerliberman** [comment]
@shawnmclean 
apparently you need to add a checkout step to your workflow
`    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
`
that seems to resolve the issue

**Comment by sudomateo** [comment]
I'll leave this issue open as I work on updating this repository with the newer YAML GitHub Actions syntax. Glad you're unblocked.

**Comment by James-Quigley** [comment]
Using the github actions converter tool (https://github.com/actions/migrate) I was able to convert my workflow to the new syntax. FWIW mine now looks like [this](https://pastebin.com/dBNauijN)

**Comment by zthomas** [comment]
If you are using https://github.com/servers-tf/infrastructure/blob/master/.github/workflows/terraform.yml
as an example you'll need to change a few things:  

- Github has deprecated `actions/checkout@v1` , use `actions/checkout@master` instead
https://github.community/t5/GitHub-API-Development-and/pull-request-check-no-longer-finding-resource/td-p/34144

Might also want to trigger on merged PR
```yaml
on:
  pull_request:
    types: [closed]
```

**Comment by sudomateo** [comment]
This has been done.
