### ISSUE TITLE
Ability to append something to git comment on terrafrom plan action

### ISSUE THREAD

**Issue by pankajagrawal16** [hashicorp/terraform-github-actions#41]
Currently we have no way of controlling some texts in comment posted when terraform plan action is executed.

This becomes a bit confusing if we run a terraform plan on multiple directories in one pull_request workflow. When terraform plan is commented by bot, it becomes difficult to figure out which directory the comment is for unless we see details of actions in action UI.

if output looks like it is below, its difficult to figure out which directory output belongs to:

![image](https://user-images.githubusercontent.com/8058415/63408750-0b42b800-c3f0-11e9-8602-70ec0f7fecc0.png)

It would be nice if we can provide some ability to append something in git comment or it by default outputs task name as well in the comment?

Is there a way around it currently ? Tried overriding env variable GITHUB_ACTION like this in task:

![image](https://user-images.githubusercontent.com/8058415/63408688-e64e4500-c3ef-11e9-8de1-66ce062fd37a.png)

But it seems that variable is overridden via task itself. Any other way?

**Comment by sudomateo** [comment]
How about adding the working directory to the comment instead?
