### ISSUE TITLE
Feature: do not post comment when not in pull_request

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-github-actions#50]
Hi,
I see the Action is trying to post the changes as a comment, but this requires the use of a file that is present which seemingly isn't there when merging, as can be seen here: https://github.com/ironPeakServices/infrastructure/commit/55d2dc2ec0d6ce210d33e2213de6e2035fd91459/checks

Can we check whether we are in a pull request (e.g. if the file exists), and if we don't skip posting the comment?

**Comment by hazcod** [comment]
The commenting also doesn't seem to work: https://github.com/ironPeakServices/infrastructure/pull/6

**Comment by lkysow** [comment]
Hi Niels,
The plan action is only designed to work on `pull_request`, not on `push`.

**Comment by lkysow** [comment]
Maybe you could try setting `TF_ACTION_COMMENT=false`. See https://www.terraform.io/docs/github-actions/actions/plan.html#environment-variables

**Comment by hazcod** [comment]
@lkysow  thanks for the info, can confirm the build runs now. (However my PR still does not list any comment)

**Comment by nathandines** [comment]
I've experienced the same issue. I've wanted to perform actions on branches before a PR is actually created in one of my workflows, and this issue will break those workflows.

Like @hazcod, I still want a comment to be written when this is running from a PR.

I've submitted #53 for review which should resolve the issue when a PR URL cannot be found.

**Comment by hazcod** [comment]
FYI, my comments were not appearing because I did not set the `GITHUB_TOKEN` env variable.
