### ISSUE TITLE
Terraform Plan - Argument List Too Long Error

### ISSUE THREAD

**Issue by brianpham** [hashicorp/terraform-github-actions#55]
Hi,

I am running into the following issue when running a plan. We are using the aws security group module which contains hundreds of security rules. Is there a workaround to make this work using github actions?

```
Plan: 663 to add, 0 to change, 0 to destroy.
------------------------------------------------------------------------
/entrypoint.sh: line 81: jq: Argument list too long
##[error]Docker run failed with exit code 126
```

Related to this closed issue, but doesn't seem like it is resolved https://github.com/hashicorp/terraform-github-actions/issues/16

**Comment by sudomateo** [comment]
These lengthy outputs are exactly why I'm rethinking how this project posts comments to pull requests. The logs are already available in the Actions tab, I'm not convinced that repeating that output in a pull request comment is necessary.

**Comment by brianpham** [comment]
Yeah, I completely agree with you @sudomateo. It would keep PR clean as well. Do you have any suggestions as a workaround the limitation at the moment?

**Comment by sudomateo** [comment]
@brianpham I _think_ you can set the `TF_ACTION_COMMENT=1` environment variable to disable commenting. That should avoid the code path that uses `jq`.

**Comment by brianpham** [comment]
Thanks @sudomateo. It is working for me now. It is good enough to just look inside the actions tab to view the plan instead of in the PR. Going to close this out.
