### ISSUE TITLE
Update documentation to reflect new YAML syntax

### ISSUE THREAD

**Issue by ethomson** [hashicorp/terraform-github-actions#67]
Hello from the GitHub Actions team!

We're really thrilled that you've been with us through the early stages of our beta.  ❤️ And as we get closer to releasing Actions publicly, we're happy that you've built this action.

However, during the beta, we've deprecated the HCL syntax.  Now workflows are [configured with a YAML configuration](https://help.github.com/en/articles/workflow-syntax-for-github-actions).

That means - unfortunately - that the examples in your documentation will not work with a GitHub Actions workflow.  We just wanted to make you aware so that you could update the documentation for your action to use the YAML workflow.  This will make sure that users can set up your action correctly and easily.

Please let us know if you have any questions about the [new syntax](https://help.github.com/en/articles/workflow-syntax-for-github-actions).  Thanks!

**Comment by booyaa** [comment]
@ethomson used your team's handy migration tool to update the starter workflow. would appreciate any feedback on improvements in the above-referenced PR. :)

**Comment by ethomson** [comment]
Awesome @booyaa!  I added one comment but otherwise I appreciate you doing this!  🙇‍♂️

**Comment by sudomateo** [comment]
Should be fixed in #88.

**Comment by ethomson** [comment]
Thanks @sudomateo!  One last question, I noticed that this isn't listed in the GitHub Marketplace for actions.  Would you be willing to list it?  I think that would be a great way to help people find your action.  Let me know if I can help.
