### ISSUE TITLE
Actions do not support Terraform Enterprise

### ISSUE THREAD

**Issue by sntxrr** [hashicorp/terraform-github-actions#9]
When following the [Terraform Enterprise Free](https://www.terraform.io/docs/enterprise/free/index.html) documentation, it suggests I create a .terraformrc file which contains my token.

These actions do not appear to support `TF_ENV_TOKEN` nor will they write an appropriately place `.terraformrc` file that would support a TFE backend 

I have a working version of a GitHub Action [https://github.com/sntxrr/create-terraformrc](https://github.com/sntxrr/create-terraformrc) that will do all the work to create the file with an appropriate secret pulled in - perhaps this technique could be integrated to support TFE style remote backends?

**Comment by lkysow** [comment]
Yes I think we should implement something exactly what you've done in https://github.com/sntxrr/create-terraformrc/blob/master/create-terraformrc

**Comment by sntxrr** [comment]
@lkysow could probably even parameterize line 15 

```
credentials "$TF_ENV_CREDENTIALS_SERVER" {
```

so that it could support not just Terraform Enterprise Free

**Comment by lkysow** [comment]
Hi Don,
So I played around with this a bit more and even if we add in the support for the environment variable, we still have the issue that free state storage is only supported in TF 0.11.12-beta. This is a problem since these actions require a stable tag from `hashicorp/terraform`.

So I'm going to sit on this for now until TF 0.11.12 is released. Until then you'll have to implement your own actions unfortunately 😞

**Comment by sntxrr** [comment]
@lkysow makes total sense - I'll just have to come back to this a bit later.  I appreciate it!

**Comment by iiro** [comment]
Any chance for an update? Now even 0.11.13 is out! :)

**Comment by lkysow** [comment]
For sure. I'm contemplating moving to golang because the bash scripts are getting long so this might not happen right away.

**Comment by sntxrr** [comment]
I support moving to `golang` - though the bash I wrote up was ~20 lines.. maybe we could do TFE support in bash, and then a larger `golang` rewrite?
