### ISSUE TITLE
TFE token support

### ISSUE THREAD

**Issue by canelkatmis** [hashicorp/terraform-github-actions#92]
It seems that v0.5.0 version cannot support tfe token. When can you add it?

**Comment by sudomateo** [comment]
Please provide more information here. What is the context in which you are using "tfe token"?

If you're looking to authenticate with the `remote` backend, check out the [examples](https://github.com/hashicorp/terraform-github-actions/tree/master/examples).

**Comment by canelkatmis** [comment]
Thank you Matthew for quick response. I couldnt see tf_cli_args
Closing...

**Comment by canelkatmis** [comment]
As you said, I meant terraform enterprise token

**Comment by sudomateo** [comment]
Thank you for following up!
